FROM ubuntu
RUN apt update -y && apt upgrade -y
RUN apt install -y wget gnupg
RUN apt install -y iputils-ping
RUN wget -qO- https://repos.influxdata.com/influxdb.key | apt-key add -
RUN echo "deb https://repos.influxdata.com/ubuntu focal stable" | tee /etc/apt/sources.list.d/influxdb.list
RUN apt update
RUN apt install -y influxdb

WORKDIR /var/influx-init
COPY ./ /var/influx-init

ENTRYPOINT [ "tools/initializeDB.sh" ]