FROM ubuntu
RUN apt update -y && apt upgrade -y
RUN apt install -y wget gnupg
RUN wget -qO- https://repos.influxdata.com/influxdb.key | apt-key add -
RUN echo "deb https://repos.influxdata.com/ubuntu focal stable" | tee /etc/apt/sources.list.d/influxdb.list
RUN apt update
RUN apt install -y influxdb

# ADD ./entrypoint.sh /tmp/entrypoint.sh
# RUN /bin/sh /tmp/entrypoint.sh
ENTRYPOINT ["influxd"]