FROM ubuntu
RUN apt update -y && apt upgrade -y
RUN apt install -y wget gnupg
RUN wget -qO- https://repos.influxdata.com/influxdb.key | apt-key add -
RUN echo "deb https://repos.influxdata.com/ubuntu focal stable" | tee /etc/apt/sources.list.d/influxdb.list
RUN apt update
RUN apt install -y iputils-ping
RUN apt install -y influxdb

ENV WORK_DIR /var/influx-init
WORKDIR $WORK_DIR
ADD ./containerScripts/initializeDB.sh $WORK_DIR

ENTRYPOINT [ "./initializeDB.sh" ]